import Head from "next/head.js"
import Homepage from "../components/Homepage.jsx"
import { useContext } from "react"
import { solpayContext } from '../components/layout';

export default function Home() {
  const { setHome } = useContext(solpayContext);
  setHome(true);
  return (
    <div>
      <Head>
        <title>Solpay</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Homepage />

    </div>
  )
}